### ISSUE TITLE
Projects can't be clicked on iPad

### ISSUE THREAD

**Issue by gustavotero7** [tomanistor/osprey#40]
Hello @tomanistor I found a new problem, if you open the page in iPad (I have tested with iPad 2017 model, safari and chrome) you can't click the portfolio items.

[Youtube video](https://www.youtube.com/watch?v=89WBStJZLZQ)
[![Osprey problem on iPad](https://img.youtube.com/vi/89WBStJZLZQ/0.jpg)](https://www.youtube.com/watch?v=89WBStJZLZQ)

Any idea what is happening here?

**Comment by gustavotero7** [comment]
PD: Check from second 12 to 21, I tap every project, nothing happen

**Comment by tomanistor** [comment]
Hey @gustavotero7, it looks like the iPad is not recognizing hover. I don't have an iPad so it's hard for me to test without a simulator but I just pushed up a fix that worked on my iPad simulator if you'd like to re-check. You should be able to now click on those portfolio items to create the hover effect present on desktops.

Thanks for finding this bug!

**Comment by gustavotero7** [comment]
Hi @tomanistor, 
Still the same problem, but I have found something else. if you do a long tap (1 sec) the "Hover" works and the gray layer comes up. Seems like on iPad the hover event is called if you hold the tap a few ms (500) or 0.5 seconds.

**Comment by tomanistor** [comment]
Gotcha, so it sounds like iPad has different events like short taps and long clicks. Currently, the hover effect is triggered by a long click.

We might have to go through all of these solutions one by one to test: https://stackoverflow.com/questions/18047353/fix-css-hover-on-iphone-ipad-ipod

However, my goal has been to eventually change the gallery items to open up a modal with more information on click. The currently links that only display on hover will then show in a modal and won't be dependent on hover. This slated for the next major release and I will leave this issue as solved for the time being.

**Comment by gustavotero7** [comment]
Yes, I have followed it, it's fixed, just added `cursor: pointer;` to the .overlay class
PR?
